### ISSUE TITLE
feature issue?

### ISSUE THREAD

**Issue by juvien** [SilvioGiancola/SoccerNet-code#15] opened 2020-03-19 04:58 UTC
Permission denied: https://drive.google.com/uc?id=1zt2-ovGDpDHB_ekeROLSJtqx2GV2BJnT
Maybe you need to change permission over 'Anyone with the link'?
  some is well some has this problems

**Comment by SilvioGiancola** [comment] 2020-03-19 11:59
duplicate of #13 :
Google Drive has a maximum bandwidth of 10TB/day. Please try again later today or tomorrow, I guess I exceeded the bandwidth for today

**Closed as completed** 2020-03-19 12:00 UTC
